### ISSUE TITLE
Redundant link are over lapping on each other

### ISSUE THREAD

**Issue by alihyder-s** [dmulyalin/N2G#13]
If i have a 2 connections between a pair of switches, it getting over lapped on each other. We have to manually drag the redudant connection & its label.

**Comment by dmulyalin** [comment]
Hi,

This is expected, as none of layout algorithms can route parallel links separately.

If you use yEd, you can try this feature to separate parallel links:
![image](https://user-images.githubusercontent.com/28857266/154228934-da5aa38c-50f4-49b9-8545-103a7f330fa5.png)

have not seen anything similar in drawio though.
