### ISSUE TITLE
Method for 'clustering' nodes as posistional argument

### ISSUE THREAD

**Issue by tmolbergen** [dmulyalin/N2G#14]
Hi, 

Im currently working on scripting this together with Ansible/LibreNMS. So far everything is looking very nice but i'm banging my head against the wall trying to group/cluster devices based on their names. 

So far Im able to identify and give the node a position but the y_pos argument dosent seem to do anything. Is the x_pos argument mandatory when y_pos has been given? 

General thought of what im trying to achieve is something along these lines;

------------------
CORE/ROUTER
------------------
SERVER/DISTRUBUTION
------------------
EDGE
------------------
servers/clients, etc

By being able to 'preplace' or group the device it might be easier to finalize the drawing after the initial creation. I was hoping I could use the y_pos argument to place it along an axis and it would automaticly preplace the nodes along this line. 

Any thoughts or suggestions would be greatly appriciated

**Comment by dmulyalin** [comment]
Hi, could you share sample code you are running to recreate the issue, x_pos and y_pos does not have to be provided at the same time.

**Comment by tmolbergen** [comment]
Hi, 

I'm not sure if its necessarily an issue. Regardless I've created an example of what I'm trying to recreate. 
[n2gexample-NOalgo.txt](https://github.com/dmulyalin/N2G/files/8122367/n2gexample-NOalgo.txt)
![image](https://user-images.githubusercontent.com/66443854/155272065-f7c4e8f0-9aaf-4c91-94c6-04711dabfd36.png)
This example clusters the nodes on top of eachother with no spacing. Expected behavior when no x_pos had been specified that it would space the nodes along the y axis. 

I would expect a result similar to this (manually edited)
![image](https://user-images.githubusercontent.com/66443854/155272195-01899969-4ee2-4d39-a261-51faae968251.png)

If I turn on layout function with kk algorithm, y_pos is completely disregarded (I was somewhat expecting this behaviour) but I was hoping it would possible to combine the layouting function with the posistional arguments, giving the algorithm a 'suggestion' on placement. 

This is the result I got
![image](https://user-images.githubusercontent.com/66443854/155272397-6148f572-6c58-4b00-be5d-956bfb727e06.png)

Reason why I'm asking for this behavior is that drawio maps have a tendency to become quite cluttered when you have larger datasets and editing them manually afterwords would be easier if you knew where x,y,z components would be placed.

**Comment by nkhambal** [comment]
Has anyone found a solution to this? x_pos and y_pos with 'kk', does not seem to work.

**Comment by dmulyalin** [comment]
I don't think `igraph` supports clustering nodes or partial layouts or grouping nodes somehow otherwise, eg based on levels/layers.  N2G however allows to pass all supported argument to layout method, but I am not seeing `y_pos` or `x_pos` as being supported argument for KK algorithm - https://igraph.org/python/versions/latest/api/igraph.GraphBase.html#layout_kamada_kawai.

If there is another library exists that supports coordinates calculation with clustering based say on node attributes, would glad to have a look at it and integrate with N2G.
