### ISSUE TITLE
Excellent Software! - one question regarding src_label and trgt_label

### ISSUE THREAD

**Issue by ncutting** [dmulyalin/N2G#15]
I am trying to send multiple lines of data to the src/dest labels.

for example, 
Gi0/1
mgt
.251

I have tried trgt_label='Gi0/1\nMTU 1500\n.251' but it appears on the same line.
I think it can be supported - because I can manually add the carriage returns in draw.io after the graph has been drawn.  
Any ideas?

![image](https://user-images.githubusercontent.com/36318580/157997291-27f07459-36e7-45dc-93ba-a4c3b83c9dee.png)

**Comment by dmulyalin** [comment]
Hi, thank you for your positive feedback, can you try `&lt;br&gt;` instead of `\n`

**Comment by ncutting** [comment]
Thank you - 
the actual code im using is in F string,  I think we are getting closer

`trgt_label =f"{interface_inner['vrf']}&lt;br&gt;{interface_inner['interface_name']}"`

![image](https://user-images.githubusercontent.com/36318580/158028111-4f16dd4e-0061-4126-8d9c-6acc8d9eafbc.png)

**Comment by ncutting** [comment]
I looked at how it looked in xml, after I changed it manually
the secret sauce is `&#xa;`

I am all good now. thank you for pointing me in the right direction
