### ISSUE TITLE
YED Grouping example requested

### ISSUE THREAD

**Issue by ppjmoors** [dmulyalin/N2G#2]
Do you have an example available that shows creating graphml graphs used in yed (yworks) for the following use cases :

1. how to create a group
2. how to add nodes to a group
3. how to add a group to a group

**Comment by dmulyalin** [comment]
Hi,

Grouping nodes or node groups not supported for yEd or DrawIO, there is some code present in N2G-yED module related to that functionality, but have not had a chance to complete it yet. Have no plans to do it anytime soon either.

As a result, no examples on how to use that functionality.
