### ISSUE TITLE
Connecting two nodes without labels on edges causes one of edges not to be created

### ISSUE THREAD

**Issue by stigmergist** [dmulyalin/N2G#5]
This is a "bug" because of the pattern of using `tuple(sorted([source,target,label]))` to create identities. Tried to fix, but see other issue on tests not passing.

Example:
```python
from N2G import drawio_diagram

diagram_dict = {
    'nodes' : [
        { 'id': 'a' , 'label' : 'A'},
        { 'id': 'b' , 'label' : 'B'},
    ],
    'edges' : [
        { 'source':'a',
          'target':'b',
          'style': 'endArrow=classic;endFill=0;sourcePortConstraint=east;targetPortConstraint=west;edgeStyle=orthogonalEdgeStyle;'
        },
        { 'source':'b',
          'target':'a',
          'style': 'endArrow=classic;endFill=0;sourcePortConstraint=east;targetPortConstraint=west;edgeStyle=orthogonalEdgeStyle;'
        },
    ]
}

diagram = drawio_diagram()
diagram.from_dict(diagram_dict)
diagram.layout('kk')
diagram.dump_file('example.drawio','./')
```

**Comment by dmulyalin** [comment]
Hi, thank you for reporting the issue.

That was a restriction in drawio module in release 0.1.2 but latest code on master brunch includes capability to add labels to links/edges for drawio diagrams - [docs](https://n2g.readthedocs.io/en/latest/DrawIo%20Module.html#quick-start) - added it as result of working on #1. If you want to test, feel free to install from master:
```
python3 -m pip install git+https://github.com/dmulyalin/N2G
```

Yet to release N2G 0.2.0, as planning to add new features and refactor the code a bit. But 0.2.0 will include capability to add src/trgt labels to edges for drawio.

**Comment by stigmergist** [comment]
Thanks for the reply. I am using the latest from master branch. These two links do not have labels (nor need them), but one is A->B and the other is B->A. They are getting collapsed into a single link (which is semantically incorrect for what I need).

I did a clean venv with the `pip install` approach and the same result.

**Comment by dmulyalin** [comment]
Ok, I see. 

Each link need to have unique ID attribute assigned, the most natural way is to use link labels and source/target nodes ID to derive link id. If several links with no labels added between same nodes, links will end up with same ID value calculated, by default second link will be skipped as a duplicate. 

Added support for optional `link_id ` attribute to `add_link `method starting with commit 78c7395d0c08b45183c1951857a2fb8b2ead7fda. `link_id ` must be unique across all links on this particular diagram.

```
from N2G import drawio_diagram as create_drawio_diagram

data = {
    "nodes": [
        {"id": "node-1"},
        {"id": "node-2"}
    ],
    "links": [
        {
            "source": "node-1", 
            "target": "node-2", 
            "link_id": 1,
            'style': 'endArrow=classic;endFill=0;sourcePortConstraint=east;targetPortConstraint=west;edgeStyle=orthogonalEdgeStyle;'
        },
        {
            "source": "node-2", 
            "target": "node-1", 
            "link_id": 2,
            'style': 'endArrow=classic;endFill=0;sourcePortConstraint=east;targetPortConstraint=west;edgeStyle=orthogonalEdgeStyle;'
        }
    ]
}    

drawio_drawing = create_drawio_diagram()
drawio_drawing.from_dict(data)
drawio_drawing.dump_file("diagram.drawio", ".")
```

**Comment by stigmergist** [comment]
Great - that works. Can work with that. Thanks.

BTW you need to add `ttp` and `openpyxl` to your package dependencies in the instructions
