### ISSUE TITLE
Building diagrams for FPrime and Feature requiests

### ISSUE THREAD

**Issue by IonRod** [dmulyalin/N2G#7]
Hy @dmulyalin !

Just want to let you know that we are using your lib in this project:
(FPrime Topology visualisation using Diagrams.Net)[https://github.com/nasa/fprime/discussions/868]

In terms of feature requests. 

It would be great to be able to create ports for nodes. Under ports I mean special attachement points for links.

**Comment by dmulyalin** [comment]
Hi @IonRod 

Glad to hear that you found N2G useful for your application.

Regarding ports for nodes, struggle to come out with use cases for them, to me it look likes hardcoding edge connection position to a certain point on the node perimeter could make diagram manual post processing difficult as edges would cross the node if node no positioned properly. Moreover, data supplied to N2G would have to contain information about port points, how that information going to be pre-calculated?
