### ISSUE TITLE
TypeError: add_link() got an unexpected keyword argument 'src_label'

### ISSUE THREAD

**Issue by loveJasmine** [dmulyalin/N2G#8]
>python da_n2g.py
Traceback (most recent call last):
  File "da_n2g.py", line 17, in <module>
    diagram.add_link("R1", "R2", label="DF", src_label="Gi1/1", trgt_label="GE23")
TypeError: add_link() got an unexpected keyword argument 'src_label'

**Comment by dmulyalin** [comment]
If you using drawio module it does support src_label only if installed from master, I am yet to release updated version of N2G
